name: Node CI Suite
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: brew update
      - run: brew cleanup
      - run: ./scripts/test
